name: Docker Build
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout docker repository
        uses: actions/checkout@v2
      - 
        name: Checkout cors-anywhere repository
        uses: actions/checkout@v2
        with: 
          repository: Rob--W/cors-anywhere
          path: cors-anywhere

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Image digest
        run: ls -al
      -
        name: Image digest
        run: ls -al ${{ env.GITHUB_WORKSPACE }}
      -
        name: Image digest
        run: ls -al ${{ env.GITHUB_WORKSPACE }}/cors-anywhere
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: yeradon/cors-anywhere:latest
          context: ${{ env.GITHUB_WORKSPACE }}/cors-anywhere
          file: ${{ env.GITHUB_WORKSPACE }}/Dockerfile
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      
  
